### ISSUE TITLE
$random コマンドにチャンネル内アクティブなメンバーのみを対象とするオプションの追加

### ISSUE THREAD

**Issue by Yu-taro** [pyconjp/pyconjpbot#7]
## 現状
`$random` : チャンネルにいるメンバーからランダムに一人を選ぶ

## 追加
`$random -active` : チャンネルにいる && 現在アクティブなメンバーからランダムに一人を選ぶ

アクティブなユーザーを取得できるか調査していないので、不可能なら却下してください。

**Comment by takanory** [comment]
あとで JIRA に移す

https://api.slack.com/methods/users.getPresence で状態は取得できるっぽい

**Comment by takanory** [comment]
https://pyconjp.atlassian.net/browse/SAR-1342
